# Generated by Django 2.1.1 on 2018-10-05 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='role',
        ),
        migrations.AlterField(
            model_name='fase',
            name='fechaInicial',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfiles',
            field=models.ManyToManyField(to='GestiRED.Rol'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
