# Generated by Django 2.1.1 on 2018-10-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0002_auto_20181004_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perfiles',
            new_name='roles',
        ),
    ]
