# Generated by Django 2.1.1 on 2018-10-05 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0003_auto_20181004_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='fechaFinal',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fase',
            name='fechaInicial',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
