# Generated by Django 2.1.1 on 2018-10-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0007_auto_20181006_1642'),
        ('GestiRED', '0006_auto_20181006_0652'),
    ]

    operations = [
    ]
