# Generated by Django 2.1.1 on 2018-10-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0015_auto_20181025_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phaseType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceType',
            field=models.IntegerField(),
        ),
    ]
