# Generated by Django 2.1.1 on 2018-10-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0016_auto_20181026_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoEvento',
            new_name='EventType',
        ),
        migrations.RenameModel(
            old_name='TipoFase',
            new_name='PhaseType',
        ),
        migrations.RenameModel(
            old_name='TipoRecurso',
            new_name='ResourceType',
        ),
    ]
