# Generated by Django 2.1.1 on 2018-10-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0019_auto_20181031_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='observation',
            field=models.CharField(default='Fase Nuevea', max_length=400),
            preserve_default=False,
        ),
    ]
