# Generated by Django 2.1.1 on 2018-11-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0020_phase_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='observation',
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='observation',
            field=models.CharField(max_length=200),
        ),
    ]
