# Generated by Django 2.1.1 on 2018-11-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0022_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='state',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
