# Generated by Django 2.1.1 on 2018-11-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0023_qualitycontrol_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='state',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
    ]
