# Generated by Django 2.1.1 on 2018-11-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0025_auto_20181101_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiRED.Resource'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phaseType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiRED.PhaseType'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiRED.Resource'),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='createUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='GestiRED.User'),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiRED.Resource'),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_user', to='GestiRED.User'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiRED.ResourceType'),
        ),
    ]
