# Generated by Django 2.1.1 on 2018-11-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestiRED', '0026_auto_20181101_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='observation',
        ),
    ]
